pipeline {
    agent any 
    
           
        
    stages {
         stage("scm"){
        
            steps {
                git credentialsId: '284cf0a3-3286-44b7-800e-4e84a4072364', url: 'https://github.com/satyamuralidhar/game-of-life.git'
            }
    
        } 
        
        stage("Build") {
            steps {
                sh label: '', script: 'mvn package'
            }
        }   
    
        stage("mail config") {
            steps {
                emailext body: '', recipientProviders: [developers()], subject: 'build', to: 'muralidhar.peddireddi@gmail.com'
            }    
        
        }
        stage("archive artifact") {
            steps {
                archiveArtifacts '**/*.war'
            }
        }
        stage('Artifactory configuration') {
            steps {
                rtServer (
                    id: "JFROG",
                    url: "http://192.168.222.135:8081/artifactory/",
                    //credentialsId: CREDENTIALS
                    username: 'admin',
                    password: 'password'
                )
                 rtMavenDeployer (
                    id: "JFROG",
                    serverId: "JFROG",
                    releaseRepo: "libs-release-local",
                    snapshotRepo: "libs-snapshot-local"
                )
            }
        }    

        stage ('Publish build info') {
            steps {
                rtPublishBuildInfo (
                    serverId: "JFROG"
                )
            }
        }
        
    
    }
    
}
