pipeline {
    agent any 
    stages {
         stage("scm"){
        
            steps {
                git credentialsId: '284cf0a3-3286-44b7-800e-4e84a4072364', url: 'https://github.com/satyamuralidhar/game-of-life.git'
            }
    
        }   
        stage("Build") {
            steps {
                sh label: '', script: 'mvn package'
            }
        }   
    
        stage("mail config") {
            steps {
                emailext body: '', recipientProviders: [developers()], subject: 'build', to: 'muralidhar.peddireddi@gmail.com'
            }    
        
        }
    }
    
}
