
pipeline {
    agent any
    
    //parameters {

        //choice(choices: [ 'master', 'dev', 'stage' ], description: 'Select deployment branch', name: 'BRANCH')
    //}

    environment{

        dockerImage = ''

        registryurl = 'muralidhar123/gameoflife-test'

        dockercred = 'dockerhub' 
    }
    

    stages {
        stage("build started") {
            steps {
                slackSend channel: 'devpoc', color: 'green', message: 'build started'
            }
        }
        stage("scm using git"){
        
            steps {
                git url: 'https://github.com/satyamuralidhar/game-of-life.git'
            }
        }
        //stage('EchoChoice'){
          //  steps{
            //    echo "${params.BRANCH}"
            //}
        //}    
       
        stage("Maven Build") {
            steps {
                sh label: '', script: 'mvn package'
            }
        }
        stage("archive artifact") {
            steps {
                archiveArtifacts '**/*.war'
            }
        }
        stage('Building image') {
            steps{
                script {
                    dockerImage = docker.build registryurl + ":$BUILD_NUMBER"
                }
            }
        }
        stage('Deploy Image') {
            steps{
                script {
                    docker.withRegistry( '', dockercred ) {
                        dockerImage.push()
                    }   
                }
            }
        }
        stage('Remove Unused docker image') {
            steps{
                sh "docker rmi $registryurl:$BUILD_NUMBER"
            }
        }
    }
       
    // slack notification  
    post {
        success {
            slackSend (color: '#00FF00', message: "SUCCESSFUL: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")

        }
        failure {
            slackSend (color: '#FF0000', message: "FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
        } 
    }        
         
} 
